# Generated by Django 4.1.5 on 2023-01-30 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Mate", max_length=100)),
                (
                    "alto",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=6, null=True
                    ),
                ),
                (
                    "ancho",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=6, null=True
                    ),
                ),
                (
                    "largo",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=6, null=True
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=6, null=True
                    ),
                ),
                ("stock", models.IntegerField(default=0)),
                ("sku", models.CharField(default="SKU 0000", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mates.color"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("material", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mates.mate"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mate",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mates.tipo"
            ),
        ),
    ]
